version: '3.7'
services:
  crawler:
    volumes:
      - ./logs:/apps/crawler/logs
    restart: always
    env_file:
      - ./prod.env
    build:
      context: .
    image: registry.cn-hangzhou.aliyuncs.com/timvel/indigo-crawler
    command: ['python3', '-u', 'app.py']
    depends_on: 
      - chrome
    networks:
      chrome-network:
        aliases:
          - crawler
    
  chrome:
    image: selenium/standalone-chrome
    container_name: chrome-selenium
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    ports:
      - '4444:4444'
    volumes:
      - '/dev/shm:/dev/shm'
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
    restart: always
    networks:
      chrome-network:
        aliases:
          - chrome

networks:
  chrome-network:
