version: '3.7'
services:
  crawler:
    volumes:
      - ./src:/apps/crawler
    restart: always
    env_file:
      - ./prod.env
    build:
      context: .
    image: meanless/indigo_crawler
    working_dir: /apps/crawler
    command: ['python3', '-u', 'app.py']
    networks:
      chrome-network:
        aliases:
          - crawler

networks:
  chrome-network:
    external: true
    name: 'chrome-network'
