version: '3.7'
services:
  crawler:
    volumes:
      - ./src:/apps/crawler
    ports:
      - '5001:5001'
    restart: always
    env_file:
      - ./prod.env
    build:
      context: .
    image: meanless/indigo_crawler
    working_dir: /apps/crawler
    command: ['python3', '-u', 'cron_job.py']
    depends_on:
      - mongo
      - chrome
    networks:
      internal:
        aliases:
          - crawler

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    env_file:
      - ./prod.env
    volumes:
      - ./data:/data/db
    networks:
      internal:
        aliases:
          - db
  chrome:
    image: selenium/standalone-chrome
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    ports:
      - 4444:4444
    volumes: 
      - '/dev/shm:/dev/shm'
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
    restart: always
    networks:
      internal:
        aliases:
          - chrome

networks:
  internal:
