version: '3.7'
services:
  crawler:
    volumes:
      - ./src:/apps/crawler/dataValidator/src
      - ../common:/apps/crawler/common
      - ./logs:/apps/crawler/detailCrawler/logs
    restart: always
    env_file:
      - ../prod.env
    build:
      context: .
    image: meanless/indigo_crawler
    working_dir: /apps/crawler/dataValidator/src
    container_name: 'sh-validator'
    command: ['python3', '-u', 'app.py']
    networks:
      chrome-network:
        aliases:
          - dataValidator

networks:
  chrome-network:
    external: true
    name: 'chrome-network'
