ERROR_AWAIT_TIME = 60*3
TASK_DONE_AWAIT_TIME = 60*15

DATA_VALIDATOR_AWAIT_TIME = 60*5

DETAIL_CRAWLER_AWAIT_TIME = 60*5

URL_CRAWLER_AWAIT_TIME = 60*15

URL_CRAWLER_TASK_DOWN_AWAIT_TIME = 60*30

URL_CRAWLER_TASK_BY_METRO = 'by_metro'

URL_CRAWLER_TASK_BY_BIZCIRCLE = 'by_bizcircle'

URL_CRAWLER_TASK_BY_LATEST = 'by_latest'
