version: '3.7'

services:
  chrome:
    image: selenium/standalone-chrome
    container_name: 'chrome-selenium'
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    ports:
      - '4444:4444'
    volumes:
      - '/dev/shm:/dev/shm'
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
    restart: always
    networks:
      chrome-network:
        aliases:
          - chrome

networks:
  chrome-network:
    external: true
    name: 'chrome-network'
